### ISSUE TITLE
Invalid request: Content longer than specified

### ISSUE THREAD

**Issue by ndr-brt** [Fraunhofer-AISEC/omejdn-server#69]
**omejdn-version**: 1.7.1

Hi, we're using omejdn-server in out test environment with some [EDC](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector) instances.
Sometimes (like 2 calls out of 30) we get this error on the server:
```
2022-10-10 08:47:56 +0000 Invalid request: Content longer than specified
  /usr/local/bundle/gems/thin-1.8.1/lib/thin/request.rb:79:in `parse'
  /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
  /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
  /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
  /usr/local/bundle/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
  /usr/local/bundle/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
  /usr/local/bundle/gems/thin-1.8.1/lib/rack/handler/thin.rb:22:in `run'
  /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1565:in `start_server'
  /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1499:in `run!'
  /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/main.rb:45:in `block in <module:Sinatra>' 
```

that results in a timeout on the EDC side.
What could be the issue?

full deployment configuration
```yaml
  clients.yml: |-
    ---
    - client_id: the-client-id
      name: omejdn admin ui
      client_secret: the-client-secret
      token_endpoint_auth_method: client_secret_post
      attributes:
      - key: omejdn
        value: admin
      redirect_uris:
      - https://example.org/callback01
      - https://example.org/callback02
      - https://oauth.pstmn.io/v1/callback
      - "/"
      scope:
      - omejdn:admin
      grant_types:
      - client_credentials
  omejdn.yml: |-
    ---
    issuer: https://daps.dev.demo.mydomain.com
    front_url: https://daps.dev.demo.mydomain.com
    bind_to: 0.0.0.0:4567
    environment: development
    openid: false
    default_audience: idsc:IDS_CONNECTORS_ALL
    accept_audience:
    - https://daps.dev.demo.mydomain.com/
    - https://daps.dev.demo.mydomain.com/token
    - idsc:IDS_CONNECTORS_ALL
    access_token:
     expiration: 3600
     algorithm: RS256
    id_token:
     expiration: 3600
     algorithm: RS256
    user_backend:
    - yaml
  plugins.yml: |-
    ---
    plugins:
      admin_api:
      token_user_attributes:
        skip_access_token: false
        skip_id_token: false
  scope_mapping.yml: |-
    ---
    plugins:
    omejdn:read:
    - omejdn
    omejdn:write:
    - omejdn
    omejdn:admin:
    - omejdn
    profile:
    - name
    - family_name
    - given_name
    - middle_name
    - nickname
    - preferred_username
    - profile
    - picture
    - website
    - gender
    - birthdate
    - zoneinfo
    - locale
    - updated_at
    email:
    - email
    - email_verified
    address:
    - formatted
    - street_address
    - locality
    - region
    - postal_code
    - country
    phone:
    - phone_number
    - phone_number_verified
    idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
    - "@type"
    - "@context"
    - "securityProfile"
    - "referringConnector"
```
