### ISSUE TITLE
The ```resource_owner.attributes``` field used by ```filter_scopes``` is not a ```Hash```

### ISSUE THREAD

**Issue by IcarusCoding** [Fraunhofer-AISEC/omejdn-server#77]
The current ```filter_scopes``` function execution results in a HTTP 500 when the ```/consent``` endpoint is called. 
I am not sure if that is caused by a configuration error on my side though.
```ruby
def filter_scopes(resource_owner, client, scopes)
  scope_mapping = Config.read_config CONFIG_SECTION_SCOPE_MAPPING, {}
  ((scopes || []) & [*client.metadata['scope']]).select do |s|
    if s == 'openid'
      true
    elsif s.include? ':'
      key, value = s.split(':', 2)
      av = resource_owner.attributes[key] # <--  resource_owner.attributes.class is not a Hash; indexing with a String
      av = { 'value' => av } unless av.instance_of?(Hash)
      av && av['value'] == value
    else
      (scope_mapping[s] || []).any? { |claim| resource_owner.attributes[claim] }
    end
  end
end
```
users.yml:
```yml
---
- username: admin
  attributes:
  - key: omejdn
    value: admin
  password: "$2a$12$At/un58ws8tY7VCAyvC0zulZIwNRC.rHvUGmpOc58yhMQawBbYrvG" # password
  backend: yaml
```
clients.yml:
```yml
---
- client_id: adminUI
  client_name: Omejdn Admin UI
  client_uri: http://localhost:4200
  logo_uri: http://localhost:4200/assets/img/fhg.jpg
  grant_types:
    - authorization_code
  software_id: Omejdn Admin UI
  software_version: 0.0.0
  token_endpoint_auth_method: none
  redirect_uris: http://localhost:4200
  post_logout_redirect_uris: http://localhost:4200
  scope:
    - openid
    - omejdn:write
    - omejdn:admin
    - omejdn:read
  attributes: []
```

My proposed change [Fork](https://github.com/IcarusCoding/omejdn-server-fix):
```diff
     elsif s.include? ':'
       key, value = s.split(':', 2)
-      av = resource_owner.attributes[key]
+      av = resource_owner.attributes.find { |hash| hash['key'] == key }
       av = { 'value' => av } unless av.instance_of?(Hash)
       av && av['value'] == value
```
